os: osx
osx_image: xcode14.2
script: xcodebuild clean build test -project EssentialDeveloperProject.xcodeproj -scheme "CITests" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone 14 Pro Max'
